[package]
name = "bakkutteh"
version = "0.2.2"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
kube = { version = "1.1.0", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.25.0", features = ["latest"] }
tokio = { version = "1.45.1", features = ["full"] }
anyhow = "1.0.98"
serde_json = "1.0.140"
inquire = "0.7.5"
colored = "3"
serde_yml = "0.0.12"
