[package]
name = "bakkutteh"
version = "0.2.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.30", features = ["derive"] }
kube = { version = "0.99.0", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.24.0", features = ["latest"] }
tokio = { version = "1.43.0", features = ["full"] }
anyhow = "1.0.96"
serde_json = "1.0.139"
inquire = "0.7.5"
colored = "3"
serde_yml = "0.0.12"
