[package]
name = "bakkutteh"
version = "0.1.2"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
kube = { version = "0.97.0", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.23.0", features = ["latest"] }
tokio = { version = "1.42.0", features = ["full"] }
anyhow = "1.0.94"
serde_json = "1.0.133"
inquire = "0.7.5"
colored = "2"
serde_yml = "0.0.12"
