[package]
name = "bakkutteh"
version = "0.1.5"
edition = "2021"

[dependencies]
clap = { version = "4.5.26", features = ["derive"] }
kube = { version = "0.98.0", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.24.0", features = ["latest"] }
tokio = { version = "1.43.0", features = ["full"] }
anyhow = "1.0.95"
serde_json = "1.0.135"
inquire = "0.7.5"
colored = "2"
serde_yml = "0.0.12"
