apiVersion: v1
kind: ConfigMap
metadata:
  name: my-configmap
  namespace: default
data:
  ENV_VAR_ONE: "value1"
  ENV_VAR_TWO: "value2"
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: my-cronjob
  namespace: default
spec:
  schedule: "0 * * * *" # Runs every hour
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: my-cronjob-container
              image: alpine:3.17
              envFrom:
                - configMapRef:
                    name: my-configmap
              env:
                - name: ADDITIONAL_VAR
                  value: "additional-value"
                - name: SPECIAL_LEVEL_KEY
                  valueFrom:
                    configMapKeyRef:
                      name: my-configmap
                      # Specify the key associated with the value
                      key: ENV_VAR_ONE
              command:
                [
                  "sh",
                  "-c",
                  "echo Running with $ENV_VAR_ONE and $ENV_VAR_TWO and $SPECIAL_LEVEL_KEY",
                ]
          restartPolicy: OnFailure
