name: tests

on: [push]

jobs:
  clippy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: install clippy
        run: rustup component add clippy
      - name: clippy
        run: cargo clippy --all-features

  fmt:
    runs-on: ubuntu-latest
    container: rust:slim
    steps:
      - uses: olix0r/cargo-action-fmt/setup@v2
      - uses: actions/checkout@v2
      - run: cargo fmt -q --message-format=json | cargo-action-fmt
