name: ci

on: [push]

jobs:
  clippy:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v2
      - name: install clippy
        run: rustup component add clippy
      - name: run unit test
        run: cargo test
      - name: clippy
        run: cargo clippy --all-features
